<?php

namespace Greicodex\PhonebookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->createQueryBuilder("c");
    }
}
